export const question = [
    {number:1,content:"機械や道具を扱うことが得意だと思う。",type:"D",answer:0},
    {number:2,content:"体を動かす仕事が好きだ。",type:"D",answer:0},
    {number:3,content : "実際に手を動かして覚える方が早いと思う。",type:"D",answer:0},
    {number:4,content:"細かい理論よりも結果を重視する。",type : "D",answer:0},
    {number:5,content:"屋内より屋外での活動を好む。",type:"D",answer : 0},
    {number:6,content:"現実的に物事を考える方だ。",type:"D",answer:0},
    {number:7,content:"図面や設計図を見るのが好きだ。",type:"D",answer:0},
    {number:8,content:"手作業や工作をすると集中できる。",type:"D",answer : 0},
    {number:9,content:"チームより一人で黙々と作業する方が得意だ。",type:"D",answer:0},
    {number:10,content:"実験や実践を通して学ぶのが好きだ。",type : "D",answer:0},
    {number:11,content:"理由や仕組みを考えるのが好きだ。",type:"I",answer:0},
    {number:12,content:"データや事実に基づいて判断したい。",type:"I",answer:0},
    {number:13,content:"難しい問題を解くことにやりがいを感じる。",type:"I",answer:0},
    {number:14,content:"計画を立てて順序立てて行動するタイプだ。",type:"I",answer:0},
    {number:15,content:"新しい理論や技術に興味がある。",type:"I",answer:0},
    {number:16,content:"論理的に説明するのが得意だ。",type:"I",answer:0},
    {number:17,content:"物事の本質を深く掘り下げたくなる。",type:"I",answer:0},
    {number:18,content:"感情よりも理屈を優先する。",type:"I",answer:0},
    {number:19,content:"曖昧な状況より明確な答えがある方が好きだ。",type:"I",answer:0},
    {number:20,content:"自分の考えを分析して整理するのが得意だ。",type:"I",answer:0},
    {number:21,content:"人の話を聞くのが得意だ。",type:"S",answer:0},
    {number:22,content:"周りの人が喜ぶと自分も嬉しい。",type:"S",answer:0},
    {number:23,content:"チームで協力して目標を達成するのが好きだ。",type:"S",answer:0},
    {number:24,content:"誰かの相談に乗ることが多い。",type:"S",answer:0},
    {number:25,content:"相手の気持ちを考えて行動する方だ。",type:"S",answer:0},
    {number:26,content:"対人関係を大切にしている。",type : "S",answer:0},
    {number:27,content:"教えたり説明したりするのが得意だ。",type:"S",answer:0},
    {number:28,content:"相手の立場に立って考えるよう心がけている。",type:"S",answer:0},
    {number:29,content:"雰囲気が悪いと気になってしまう。",type:"S",answer:0},
    {number:30,content:"誰かをサポートする仕事に魅力を感じる。",type:"S",answer:0},
    {number:31,content:"自分なりのやり方を工夫するのが好きだ。",type:"C",answer:0},
    {number:32,content:"芸術やデザインに興味がある。",type:"C",answer:0},
    {number:33,content:"感覚的に「いい」と思ったことを大切にする。",type:"C",answer:0},
    {number:34,content:"他の人と違う視点で物事を見たい。",type:"C",answer:0},
    {number:35,content:"自由な発想でアイデアを出すのが得意だ。",type:"C",answer:0},
    {number:36,content:"表現すること（絵・音楽・文章など）が好きだ。",type:"C",answer:0},
    {number:37,content:"新しいことに挑戦するのがワクワクする。",type:"C",answer:0},
    {number:38,content:"感情を表に出すことに抵抗がない。",type:"C",answer:0},
    {number:39,content:"型にはまったルールは苦手だ。",type:"C",answer:0},
    {number:40,content:"想像したことを形にするのが好きだ。",type:"C",answer:0}
    ];

